### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by CoolLKKPS** [ButteryStancakes/ButteryFixes#1]
InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <dab7f68612224ba3ae40f651d44f9d4c>:IL_0010 
  at ModelReplacement.ViewStateManager.Awake () [0x0003f] in <5307236d89244ff1b3d9a1e0dd474653>:IL_003F 
UnityEngine.Object:Internal_CloneSingleWithParent(Object, Transform, Boolean)
UnityEngine.Object:DMD<UnityEngine.Object::Instantiate>(Object, Transform, Boolean)
UnityEngine.Object:Instantiate(GameObject, Transform, Boolean)
UnityEngine.Object:Instantiate(GameObject, Transform)
TooManyEmotes.UI.<<InitializePlayerCloneRenderObject>g__InitPlayerCloneAfterSpawnAnimation|0>d:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by CoolLKKPS** [comment]
@ButteryStancakes

**Comment by CoolLKKPS** [comment]
@ButteryStancakes u just need to pull the lever, and u will see this log after the game are finished the load

**Comment by ButteryStancakes** [comment]
Does this issue only occur when ButteryFixes is enabled? The error explicitly mentions `TooManyEmotes`, so it'd help if you can verify that it doesn't occur due to a conflict with the rest of your profile

**Comment by CoolLKKPS** [comment]
with 1.2.3 butteryfixes this wont happen, maybe u need my modpack profile

**Comment by ButteryStancakes** [comment]
That's certainly good to know. Still not sure what the problem is, just looking at your error - a profile code would definitely help me out. :)

**Comment by CoolLKKPS** [comment]
@ButteryStancakes im not export by using code, instead i store my profile in a onedrive share link: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h
i will update my modpack after about 10 mins, and most time i update this modpack everyday
u need to update ur mod in my modpack to reproduce the issue, and i d sug don't update other mods

**Comment by ButteryStancakes** [comment]
Sure. I was poking around a little bit in the other mods mentioned in your log, and maybe have an idea of what could help? We shall see

**Comment by CoolLKKPS** [comment]
Updated

**Comment by CoolLKKPS** [comment]
if u want to make some debug logs show in the log console, change the log level in "lesslog.cfg", will update again for slightly log improvement, "disableunitylog" mod doesn't enabled even u see this mod are loaded, the reason to keep that mod is for very very poor devices when playing (i have one, and honestly log spamming did can drop the framerate), i already filter many trash logs for easy diagnosis, to see what logs are filtered, check "BlueAmulet.LogNeuter.cfg"

**Comment by ButteryStancakes** [comment]
Unfortunately, your profile is entirely too big for me to test - it took about half an hour to open, then crashed before reaching the title screen (with about 9GB of ram usage) - I don't have the best hardware and I especially don't have the time to keep relaunching this every time I need to test out a potential solution.

I _do_ think I know a smaller subset of mods that might be able to recreate your issue, so I'm going to try poking around a bit more, especially with the changes I'm making in v1.3.1 - but that's the best I think I can offer, at the moment

**Comment by CoolLKKPS** [comment]
uh i did know what happen, u need at least 30 GB in order to run this modpack, but no reason it will took half hour

**Comment by CoolLKKPS** [comment]
set Visual Memory to 25 GB or higher, that should work
or uninstall black mesa mod

**Comment by CoolLKKPS** [comment]
im using fx8300, gtx1050 with 8gb ddr3, only took 3 mins, no reason it took half hour really

**Comment by CoolLKKPS** [comment]
:(  sorry i can't help much for this, that's the requirement that i didn't mention, i can't do more better between quality and performance, and cache files will took the disk space about 9 GB, that's for boosting startup speed

**Comment by ButteryStancakes** [comment]
I believe I have fixed your issue in v1.3.1. Once it's available for download on Thunderstore, let me know if your game works again (or, if it produces a new error message, send that my way too)

**Comment by CoolLKKPS** [comment]
This issue fixed, updating modpack
