### ISSUE TITLE
[Request] Make the fire exit fix toggleable

### ISSUE THREAD

**Issue by zndrmn** [ButteryStancakes/ButteryFixes#11]
I believe fire exits spawning you in backwards kinda balances them out a bit because then there's a risk to going in that way since there's a chance you can just get yoinked by a bracken or ran over by a coil head.
Idk I'm just super used to flicking my mouse when entering through a fire exit. I really hope this becomes a toggleable option in the config.

**Comment by ButteryStancakes** [comment]
This is already a config setting ("FixFireExits" under "Gameplay")

**Comment by zndrmn** [comment]
oh sorry I guess I missed it
