### ISSUE TITLE
[Bug] The Ship icon on radar appear when spectating players who died inside

### ISSUE THREAD

**Issue by MiraakThuri** [ButteryStancakes/ButteryFixes#12]
When you spectate dead players, the newly restored ship icon will display on the radar when a player is dead, even if he died inside the factory/manor
When it should only display outside

**Comment by ButteryStancakes** [comment]
This is technically a vanilla bug, it's just a lot less noticeable when you don't have the ship icon on-screen. I will take a look at improving this in the future

**Comment by ButteryStancakes** [comment]
I have finally addressed this in v1.8.0. Sorry for the delay
