### ISSUE TITLE
[Question] Snow map detection code (for boulder visuals)

### ISSUE THREAD

**Issue by MiraakThuri** [ButteryStancakes/ButteryFixes#13]
Hey, i noticed that your SnowyHolidayDropship mod is able to correctly detect custom snow maps (probably thanks to the "levelIncludesSnowFootprints" i suppose), would it be possible to use that for the boulder code so the appearance fix can also work on custom snow maps instead of using the hard codded map names ?

**Comment by ButteryStancakes** [comment]
It would be possible but I decided to play it safe because it could cause issues if a level erroneously sets the snow footprints flag without actually having snowy terrain. If you aren't aware of any pre-existing conflicts with SnowyHolidayDropship, I could probably just take the gamble

**Comment by MiraakThuri** [comment]
Well i personally never got any issue with SnowyHolidayDropship generating the wrong model or track
so ofc i can't vouch for every custom map out there but it always worked perfectly for me

**Comment by ButteryStancakes** [comment]
Probably I will do this in the next update then. :)

**Comment by ButteryStancakes** [comment]
v1.7.1 includes this change
