### ISSUE TITLE
[Fatal] Can't start game in March when install v1.7.0 and v1.7.1

### ISSUE THREAD

**Issue by NakiriFox** [ButteryStancakes/ButteryFixes#14]
[15:08:39.4711035] [Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
ButteryFixes.Utility.SceneOverrides.SwapEntranceDoors () (at <375314089dca4de68bc4821260221472>:IL_000F)
ButteryFixes.Patches.General.RoundManagerPatches.PostGenerateNewFloor () (at <375314089dca4de68bc4821260221472>:IL_0000)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?2009601064(RoundManager)
LethalLib.Modules.Dungeon.RoundManager_GenerateNewFloor (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <64fae9f52f324ab2a8065723b0759a64>:IL_010B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?1681827124(RoundManager)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager,int,int,int,int,int[])
RoundManager.__rpc_handler_3073943002 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <c9d7e026adb34f2d9ff3c345b08b6a12>:IL_00A7)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[15:08:39.4741039] [Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
ButteryFixes.Utility.SceneOverrides.SwapEntranceDoors () (at <375314089dca4de68bc4821260221472>:IL_000F)
ButteryFixes.Patches.General.RoundManagerPatches.PostGenerateNewFloor () (at <375314089dca4de68bc4821260221472>:IL_0000)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?2009601064(RoundManager)
LethalLib.Modules.Dungeon.RoundManager_GenerateNewFloor (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <64fae9f52f324ab2a8065723b0759a64>:IL_010B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?1681827124(RoundManager)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager,int,int,int,int,int[])
RoundManager+<LoadNewLevelWait>d__131.MoveNext () (at <c9d7e026adb34f2d9ff3c345b08b6a12>:IL_0244)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[15:08:39.4751018] [Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
ButteryFixes.Utility.SceneOverrides.SwapEntranceDoors () (at <375314089dca4de68bc4821260221472>:IL_000F)
ButteryFixes.Patches.General.RoundManagerPatches.PostGenerateNewFloor () (at <375314089dca4de68bc4821260221472>:IL_0000)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewFloor>(RoundManager)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<RoundManager::GenerateNewFloor>?2009601064(RoundManager)
LethalLib.Modules.Dungeon.RoundManager_GenerateNewFloor (On.RoundManager+orig_GenerateNewFloor orig, RoundManager self) (at <64fae9f52f324ab2a8065723b0759a64>:IL_010B)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoundManager::GenerateNewFloor>?1681827124(RoundManager)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::GenerateNewLevelClientRpc>(RoundManager,int,int,int,int,int[])
RoundManager+<LoadNewLevelWait>d__131.MoveNext () (at <c9d7e026adb34f2d9ff3c345b08b6a12>:IL_0244)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by NakiriFox** [comment]
v1.6.2 works perfectly.

**Comment by NakiriFox** [comment]
After confirm the change of moons on the terminal, I quickly exit the terminal.
Then hold down E on the lever before switching between moons is complete.
After pulling down the lever, the error occurred.

**Comment by ButteryStancakes** [comment]
Oh I think I goofed something if you try to land on March. That's my bad, I will hotfix this in just a minute

**Comment by ButteryStancakes** [comment]
Very sorry about the trouble here. :(
I have just pushed v1.7.2 to Thunderstore which fixes this issue for March (and the code is a bit safer, so it should work for custom moons as well, if they'd previously exhibited this issue)
