### ISSUE TITLE
[Conflict] new update break Celestial Tint by sfDesat

### ISSUE THREAD

**Issue by CoolLKKPS** [ButteryStancakes/ButteryFixes#17]
@ButteryStancakes same as topic

**Comment by CoolLKKPS** [comment]
can u make a quick update to fix this or disable some feature to prevent conflict?

**Comment by ButteryStancakes** [comment]
Yeah I just became aware of this. I will post a hotfix to deal with this in a few minutes. Sorry for the inconvenience

**Comment by CoolLKKPS** [comment]
glad to see your quick response, u r a true dev

**Comment by ButteryStancakes** [comment]
Ok, it took a little bit because I was looking into a loosely related issue, but I have released v1.10.7 which resolves this incompatibility.

**Comment by CoolLKKPS** [comment]
nice!
