### ISSUE TITLE
Scan node for Apparatus does not change based on actual value

### ISSUE THREAD

**Issue by tesinormed** [ButteryStancakes/ButteryFixes#2]
# Description

When using the scanner on an Apparatus, the value shown is always ▮80 (see note 1). It does not change based on the actual value of the item, which can vary based on other mods. For example, FacilityMeltdown ([GitHub](https://github.com/LoafOrc/FacilityMeltdown), [Thunderstore](https://thunderstore.io/c/lethal-company/p/loaforc/FacilityMeltdown/)) changes the value of the Apparatus to at least ▮240.

## Notes

1. Only after saving and then loading.

# Issue location in code

See [`Patches/ItemPatches.cs` from line 192 to line 203](https://github.com/ButteryStancakes/ButteryFixes/blob/master/Patches/ItemPatches.cs#L192-L203).

# Ways to fix

1. Setting the scan node's text to the actual value of the item.
2. Adding a configuration option to disable the modification of the scan node.

**Comment by ButteryStancakes** [comment]
Yes, I realized that changing it's value to always read $80 was sort of shortsighted. I've already addressed this in v1.3.1 but I'm still sitting on it at the moment. Hopefully will go live shortly :)

**Comment by ButteryStancakes** [comment]
This should be fixed in v1.3.1. Please test again and let me know (once it shows up for download on Thunderstore; it appears to be experiencing an outage right now)
