### ISSUE TITLE
[Request] Config toggle for v1.4.0 hoarder bug aggro fix

### ISSUE THREAD

**Issue by MathiusXII** [ButteryStancakes/ButteryFixes#4]
I assume this disables the behavior of hoarder bugs where they would aggro if you had a lot of items on you and you get close. 
I kind of like that behavior since it's like they're jealous of all your loot and are trying to rob you.

Could you add a toggle for this? Thanks.

**Comment by ButteryStancakes** [comment]
No, it fixes a bug where if you steal items from hoarding bugs and quit to main menu, they will automatically aggro on you the next day you host. They still aggro on you if you get too close to them. This is an intended feature and not something I plan to change. :)

**Comment by MathiusXII** [comment]
Ahh ok. Never mind then.
