### ISSUE TITLE
[suggest] When scanning out Tooltips and quickly removing them from sight, the position of Tooltips will incorrect. Need fix for this issue.

### ISSUE THREAD

**Issue by NakiriFox** [ButteryStancakes/ButteryFixes#7]
![1](https://github.com/user-attachments/assets/733a7d31-8549-46fe-89a7-664f6a4a2528)
The tooltips that were just scanned.
![2](https://github.com/user-attachments/assets/c1d6f2d7-257c-4161-89a6-641934df40b8)
After moving out of sight, tooltips appear from the other side.

If install the mod that increase the scanning range, this situation will be even more severe.

**Comment by NakiriFox** [comment]
And after increasing the scanning range, some items behind players will also be scanned, which will directly trigger the above problem.

Can we make the tooltips disappear in the correct situation？
If possible, I hope the scanning range can be limited to the front of the player.

**Comment by NakiriFox** [comment]
https://thunderstore.io/c/lethal-company/p/TheSecretDev/Unlimited_Scan/
This mod fixes the above two issues :)

**Comment by MiraakThuri** [comment]
I don't think that should be closed as the mod you linked does more than just fixing this bug
what do you think @ButteryStancakes ?

**Comment by NakiriFox** [comment]
> I don't think that should be closed as the mod you linked does more than just fixing this bug what do you think @ButteryStancakes ?

Unlimited Scan is not really unlimited, it just adds a little distance appropriately which will not disrupt the balance of the game.

If you don't want to extend the scanning distance, use this👇
https://thunderstore.io/c/lethal-company/p/TestAccount666/GoodItemScan/

By appropriate configuration, this can not only solve the above problems, but also reduce the performance consumption of scanning👇
![QQ_1722482831643](https://github.com/user-attachments/assets/d42c8eb2-1b39-4df1-93eb-c5e636c012c1)

I have installed both Unlimited Scan and GoodItemScan simultaneously, this can bring the most balanced and user-friendly scanning.

**Comment by NakiriFox** [comment]
However, there is still one issue waiting to be fixed.
![QQ_1722482831643](https://github.com/user-attachments/assets/30588972-7349-4ae5-851a-53c6ae98c628)

There are two mods👇 attempting to fix this issue
GoodItemScan: Hide Empty Scan Node Sub Text
GeneralImprovements: HideEmptySubtextOfScanNodes

I have tried different combinations of activation, but they all failed

**Comment by NakiriFox** [comment]
However, there is still one issue waiting to be fixed.
![QQ20240801-114029](https://github.com/user-attachments/assets/54dbe8f0-dc48-4bcc-878c-b67569c62dfb)


There are two mods👇 attempting to fix this issue
GoodItemScan: Hide Empty Scan Node Sub Text
GeneralImprovements: HideEmptySubtextOfScanNodes

I have tried different combinations of activation, but they all failed

**Comment by NakiriFox** [comment]
Perhaps you can fix all three of these issues simultaneously?

**Comment by ButteryStancakes** [comment]
I don't plan on messing with the scanner, since it's kind of complicated and prone to breaking easily, or having bad performance if you add too much additional functionality. I suggest either using GeneralImprovements for the FixPersonalScanner setting, or just the GoodItemScan mod as mentioned above

**Comment by NakiriFox** [comment]
The third issue is caused by the translation mod :(
